---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"


- include_tasks: install_deps.yml


- include_tasks: install_lmod.yml
  when: install_lmod

# this fails with nfs install cause of root_squash
- name: Link files to /etc/profile.d
  ansible.builtin.file:
    src: "{{ lmod_prefix }}/lmod/lmod/init/{{ item.src }}"
    dest: "/etc/profile.d/{{ item.dest }}"
    state: link
    mode: 0644
    owner: root
    group: root
  with_items:
    - {src: profile, dest: z00_lmod.sh}


- name: Adept /etc/bash.bashrc
  ansible.builtin.blockinfile:
    path: /etc/bash.bashrc
    state: present
    block: |
      if ! shopt -q login_shell; then
        if [ -d /etc/profile.d ]; then
          for i in /etc/profile.d/*.sh; do
            if [ -r $i ]; then
              . $i
            fi
          done
        fi
      fi
  when: ansible_os_family == Debian

# for redhat all users should have this in their bashrc
# if [ -f /etc/bashrc ]; then
#    . /etc/bashrc
# fi